# -*- coding: utf-8 -*-
"""Multi-Domain Data Analysis Portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yxrhveOYbn0-5KMat2YCSXu-vwg__e94
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df_retail = pd.read_csv('/content/supermarket_sales.csv')

# Basic Data Quality Check
print("Dataset Info:")
print(df_retail.info())

# Convert Date and Time to datetime objects
df_retail['Date'] = pd.to_datetime(df_retail['Date'])
df_retail['Time'] = pd.to_datetime(df_retail['Time']).dt.time

# Check for missing values
print("\nMissing values per column:")
print(df_retail.isnull().sum())

display(df_retail.head())

# 1. Sales by Product Line
plt.figure(figsize=(10, 6))
sns.barplot(x='Product_Line', y='Total', data=df_retail, estimator=sum, errorbar=None, palette='viridis')
plt.title('Total Revenue by Product Line')
plt.xticks(rotation=45)
plt.show()

# 2. Daily Sales Trend
daily_sales = df_retail.groupby('Date')['Total'].sum().reset_index()
plt.figure(figsize=(12, 5))
sns.lineplot(x='Date', y='Total', data=daily_sales, color='teal')
plt.title('Daily Sales Performance')
plt.show()

# 3. Customer Gender vs Payment Method
plt.figure(figsize=(10, 6))
sns.countplot(x='Payment', hue='Gender', data=df_retail, palette='magma')
plt.title('Payment Method Preference by Gender')
plt.show()

"""### Executive Summary: Supermarket Sales Analysis

**Business Insights:**
1. **High-Value Categories:** Identifying which product lines contribute the most to the bottom line allows for better inventory allocation.
2. **Sales Volatility:** The line chart highlights specific peaks in daily sales, which can be correlated with weekend promotions or local events.
3. **Payment Behavior:** Understanding how different demographics (Gender) prefer to pay (E-wallet, Cash, Credit Card) helps in optimizing point-of-sale checkout experiences.

**Recommendations:**
* Focus marketing spend on the highest-performing Product Lines.
* Implement targeted loyalty offers for the preferred payment methods identified.
"""